alertingRules:
  groups:
    - name: custom-alerts
      rules:
        - alert: HighCPU
          expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 85
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage"
